apiVersion: v1
kind: Service
metadata:
  name: {{ include "vas.fullname" . }}-service
  labels:
    {{- include "vas.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.exposePort }}
      name: {{ .Values.service.name }}
      targetPort: {{ .Values.service.port}}
    - name: app
      port: {{ .Values.service.port}}
  selector:
    {{- include "vas.selectorLabels" . | nindent 4 }}