{{- if .Values.applicationSecret.enabled -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vas.applicationSecret.name" . }}
type: Opaque
stringData:
  keycloakClientSecret: {{  .Values.applicationSecret.clientSecret }}
  keycloakClientId:  {{  .Values.applicationSecret.clientId }}

{{- end }}